### ISSUE TITLE
Problems with exporting TIFF Charts

### ISSUE THREAD

**Issue by pakthan** [mipastgt/AIPBrowserDE-Public#13]
Hi!
Thank you very much for this wonderful tool!

I don't know, if it is a bug or just my lack of knowledge...

I am using a JSON File to create an export of all approach charts for the german airfields.
everything works just fine, but no matter which "imageFormat" is chosen, it always exports into Geo-PDF.

To use it in Enroute, I need it as GEO-TIFF... the single export function works just fine and I get the desired TIFF.

Maybe someone can give me a hint, what I am doing wrong?

Here is my actual JSON:
{
    "version": "1.0.2",
    "name":"AIP-VFR-Germany _TIF",
    "description": "The whole AIP-VFR of Germany TIF",
    "type": "FFCP",
    "pages": {
        "coveredArea": [
            {
                "type": "GeoRectangle",
                "west": 5.0,
                "south": 47.0,
                "east": 16.0,
                "north": 56.0
            }
        ],
        "asSingleFile": true
    },
    "charts": {
        "coveredArea": [
            {
                "type": "GeoRectangle",
                "west": 5.0,
                "south": 47.0,
                "east": 16.0,
                "north": 56.0
            }
        ],
        "minInvScale":  10000.0,
        "maxInvScale": 500000.0,
        "imageFormat": "tiff"
    }
}

**Comment by mipastgt** [comment]
It's not a bug, it's a feature :-). The example configuration from which you have created this one was explicitly made for ForeFlight and thus produces data in a format which only ForeFlight understands directly. Therefore the `imageFormat` is ignored and substituted by Geo-PDF. Enroute requires a native Trip-Kit which you can get by default if you just remove the line
`"type": "FFCP",`
In addition, Enroute does not require TIFF files when you are creating a whole Trip-Kit. Actually I would advise you not to use TIFF for that purpose because of its size and because we recently found out that not all Android versions do support TIFF. See: 
https://github.com/Akaflieg-Freiburg/enroute/issues/385
It's better to use "webp" instead. ("png" or "jpg" would work too.)
I am also not sure whether you want `"asSingleFile": true` because that will result in a very large document which may be hard to handle. I have attached a zipped, working config file below. (You have to unzip it first before you can use it.)
[trip-kit-config-AIP-VFR-Germany-native.json.zip](https://github.com/mipastgt/AIPBrowserDE-Public/files/14521226/trip-kit-config-AIP-VFR-Germany-native.json.zip)

**Comment by pakthan** [comment]
Thank you very much for the really fast response and perfect answer!
And sorry for my stupid mistake...  I should have read the basic section more carefully!

Everything works like a charm and saves a lot of memory space.
To have all approach charts with me makes it much mor easy for a backup solution to my paper charts.

--> Little note: When you try to import the Tripkit into EFN via the "open with..." function of the android V12 device it will crash and give you an exception error à la " Type of File XYZ is not recognized"
You have to use the import way under Library - VAC

**Comment by mipastgt** [comment]
Maybe you can also report the "little note" here: https://github.com/Akaflieg-Freiburg/enroute/issues
