### ISSUE TITLE
Is there a project for georeferencing the Taxi-Terminal Charts?

### ISSUE THREAD

**Issue by pakthan** [mipastgt/AIPBrowserDE-Public#14]
Hi!
The title should be very selfexplainatory ...
Because of the lack of geocoordinates the airfield maps are not georeferenced .
The missing degree scales at the map border makes it very hard for an really correct alignment to use it as a rolling-aid on big Airports.

Is there a project or team, which works on that already? 
About 1000 airfields is a lot of calibrating... and GoogleEarth clicking...

**Comment by mipastgt** [comment]
There is currently no such project on our side for various reasons.
1. We are currently trying to improve the software infrastructure to be able to support more general georeferencing concepts.
2. Georeferencing the aerodrome maps makes only sense if it is very accurate.
3. We still have to decide whether it is really worth the effort. The aerodrome maps only make sense for the bigger airports. For the smaller ones they only contain little information which doesn't seem to justify the enormous effort.
4. Technically it would also make more sense to georeference the PDF charts of the bigger airports from the AIP IFR, which are of much better quality. (I have no idea why the DFS is not doing that themselves because it would be very little effort for them as they already have all the data anyway.)

**Comment by pakthan** [comment]
Sounds absolutely legit to me!

I would try to reference the EDD_ airports, because it is the only area, where it is slightly useful... especially by night...
Is there a Database, where I could share the coordinates of the referencepoints?
How do the normal approach charts save their reference and cutout data which is native preselected?

**Comment by mipastgt** [comment]
The georeferencing data can be imported/exported as a JSON file on the "settings" page. To see the format just press the button "Export". In order to georeference the EDD_ airports you would just have to use three reference points instead of two. Three reference points uniquely define an affine transformation, which would allow rotation and shearing in addition to shifting and scaling. But a few words of caution:
1. The current version of the software cannot handle more than two points at the moment. (But I am working on that.)
2. Some output formats (VFRNav and SimpleVFR) conceptionally cannot handle transforms with shearing or rotation.
3. The DFS very often invalidates the georeferencing without any reason when they make slight changes (I have to manually correct some maps every 28 days. So, you will have to support it for a life-time :-))
If you are still interested give me a ping and I'll have a look at what I can do over the weekend.

**Comment by mipastgt** [comment]
I spent the weekend working on the software and with some other software of mine I can now georeference the aerodrome charts too and **AIP Browser DE** can read this data and export single charts or whole trip-kits containing this data. The following image shows the chart of Hannover 5, exported from **AIP Browser DE**, on top of a satellite image for verification.
![mpcopilot_verify_eddv5](https://github.com/mipastgt/AIPBrowserDE-Public/assets/16735714/e1ecc822-b728-4575-a520-5a7b04069946)
So, I can confirm that there is a project now to also georeference the aerodrome charts of the larger EDD_ airports.
I will follow this [list of larger airports](https://de.wikipedia.org/wiki/Liste_der_Verkehrsflugh%C3%A4fen_in_Deutschland#Verkehrsflugh%C3%A4fen) starting with the international airports.

**Comment by mipastgt** [comment]
So, the details charts of all the 15 larger (international) airports of germany are now georeferenced. I can make a new version of AIP Browser DE (1.1.5) available as soon as Enroute can also import them. There are still some open issues.

**Comment by pakthan** [comment]
Hi!
Sorry for my longer abstinece, but I just returned from work recently.
I am absolut stunned, what has been done in the last few weeks!
On your side as on the Enroute GIT!
Thank you VERY much for all your effort and professionalism!

I just Updated my AIP Germany an it works just as a charm! And so quick!
But I am still not able to export the Taxi-Charts ... but when I read all the discussions on GitHub, I am thinking the error must be me or my understanding...
Do I have to get a special new json file? (the aipde-aux...json) Or did you released a new version, which I can't find?

It would be very nice of you, If you could help me here once more... sorry for bothering!

**Comment by mipastgt** [comment]
The reason is that I simply haven't released version 1.1.5 yet for various reasons. But if you would like to experiment with it here are the links to the preview versions. But be warned that these are just previews.
https://mpmediasoft.de/products/AIPBrowserDE/preview/AIP%20Browser%20DE-1.1.5-b11-linux-x86_64.deb
https://mpmediasoft.de/products/AIPBrowserDE/preview/AIP%20Browser%20DE-1.1.5-b11-osx-x86_64.dmg
https://mpmediasoft.de/products/AIPBrowserDE/preview/AIP%20Browser%20DE-1.1.5-b11-windows-x86_64.msi

**Comment by pakthan** [comment]
Thank you very much for this preview!
I am treating this just as a nightly build!

To this point, I had some problems with the TripKit creation, but with both versions side by side, I am able to build everything and then create the important taxicharts by hand and add them to the Enroute VAC portfolio!
Works as a charm!

Thank you very much for your effort!

**Comment by mipastgt** [comment]
What exactly were the problems with the Trip-Kit creation? And which charts did you create by hand? I need the details to spot potential problems.

**Comment by mipastgt** [comment]
The EDD_ charts should work now by default in the new version 1.2.0
